### ISSUE TITLE
Secret expiration race condition

### ISSUE THREAD

**Issue by jhosteny** [telia-oss/sidecred#22]
I've run into a few cases where CI builds fail due to expired / missing credentials. I initially wrote this off as a race due to credentials expiring in the middle of a build, where there are multiple credential components changing (e.g., AWS STS creds).

Looking at the code, though, it now seems like there is a race between the creation expiry check, and deletion expiry check. They are first conditionally created if `hasValidCredentials` is false, then later removed if `InUse` is false, `Deposed` is true, or they expire. However, it is possible for the creds to pass the first expiry check, then fail the second. This means that a credential that expires is not re-populated until the next time the cloudevent rule runs that triggers the lambda. I'm pretty certain that this case is shown explicitly by a log I have.

I'm looking at potential fixes, but I think one is to simple delete the second expiry check in the loop that destroys credentials.

**Comment by itsdalmo** [comment]
Hi @jhosteny - thanks for the issue and your PR to fix it, appreciated as always!  I think we might still be missing the notion of a `CredentialRotationWindow` in order to fully solve your problems though? This is because `sidecred` currently waits for the credentials to actually have expired before attempting to rotate them, so we need a way to tell `sidecred` that its fine to rotate the credentials in a window prior to their expiration.

Been a while since I had a chance to dive into the code here so I might be wrong though! I'll take a closer look and hopefully submit a PR to fix this tomorrow, if I'm correct 😅

**Comment by jhosteny** [comment]
@itsdalmo ah, yes, you are correct. I'm sorry - I should have reviewed that more closely.

I think it would be great if it would be possible for the invocation to specify the refresh internal (i.e., pass it in the payload of the cloud watch rule for a each team). Obviously, this would have some small one-time windows when run for the first time, or if the interval changed. But it would allow the `CredentialRotationWindow` to be set dynamically. Does that make sense?

**Comment by jhosteny** [comment]
An easier solution is probably just to make the rotation window open when the credential is more than half (or some configurable percentage) expired.

**Comment by itsdalmo** [comment]
Added the simplest solution I could think of in the PR above @jhosteny - and added a comment which I figure should be duplicated to the issue here:
> Its a start, but I'm not sure its good enough 🤔 Another option might be to write a "last updated" to the state and use that to figure out what the rotation window needs to be in order to rotate credentials prior to their expiration - as suggested by @jhosteny.

What do you think? Should we add a "last updated" to the state and use that to figure out when the credentials need to be rotated, or is that too much magic?

**Comment by jhosteny** [comment]
Hi @itsdalmo, thanks! I like the auto-detection of the interval, but it feels like that is perhaps overkill for now.

I also pushed a branch a little bit ago that contains another potential fix which I ran with today, which just checks if more than half the interval has been used up. I'm happy if you want to merge yours, though.

The change I made has an annoying side effect for testing, which is that the equality check on the resource fails on the rotation_window (since that is set non-idempotently from a call to `Now()`). I just nulled it out for that check.

**Comment by itsdalmo** [comment]
Hey again @jhosteny! For now I have merged #24 since its the simplest solution of the two, and hopefully it is easy to reason about also, since it the rotation window needs to be adjusted in relation to how often `sidecred` executes (and how long the credentials are valid). I picked up `Expiration.Add(-rotationWindow)` from your commit by the way, much more readable - thanks 👍 

Will close this issue for now since the merge should have fixed the problem. Please reopen if I'm wrong or if you need a different solution. Thanks again!

**Comment by jhosteny** [comment]
@itsdalmo thanks, perfect!
