### ISSUE TITLE
v0.2.0 release

### ISSUE THREAD

**Issue by jhosteny** [telia-oss/sidecred#26]
Hi @itsdalmo - this has been working great for us! Would you consider tagging 0.2.0 and adding a new release?

**Comment by itsdalmo** [comment]
Hi @jhosteny I've created a release here now:
https://github.com/telia-oss/sidecred/releases/tag/v0.2.0

Sorry for the delay! Next I'll look into setting up Github Actions so that it will build and upload the artefacts to the release whenever a tagged is pushed to master so we have that for future releases.

Do you consider the `v0.2.0` release to have been enough for this issue or are you wanting the binaries as well?

**Comment by jhosteny** [comment]
@itsdalmo Thanks! I currently have a .zip that is deployed with our lambda that I built locally from master. I wanted to try to use a terraform module that pulled the .zip via curl, so I can get rid of the local artifact copy step. I will do that when the binaries are available, but this is by no means urgent for me. I can wait until you have CI set up.

It's been working great for us so far!

**Comment by itsdalmo** [comment]
@jhosteny I've added a [v0.2.1](https://github.com/telia-oss/sidecred/releases/tag/v0.2.1) release now that includes artefacts. Feel free to try it out, and please open an issue if you have any problems 👍
